---
#-------------------------------
# General Site Settings

title: ChipMaster Việt Nam
logo: assets/images/logo/logo-home.png
author: chipmastervn
description: Unleash the potential of Silicon
email: chipmastervn@gmail.com
phone: +84 869 902 096
address: Dong Anh District, Hanoi, Vietnam
# copyright: Copyright &copy; 2023 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: VỀ CHÚNG TÔI, link: "/about" }
  - { name: KHÓA HỌC, link: "/courses" }
  - { name: TÀI LIỆU, link: "/documents" }
  - { name: DỊCH VỤ, link: "/services" }
  - { name: BLOG, link: "/blog" }
  - { name: TIN TỨC, link: "/news" }
  - { name: LIÊN HỆ, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  # hero-title: Xin chào!<br> Chúng tôi là <br> ChipMaster Việt Nam <br>
  hero-title-1: Xin chào!<br> Chúng tôi là
  hero-title-2: ChipMaster Việt Nam <br>

social:
  - { icon: "ti-facebook", link: "https://www.facebook.com/profile.php?id=61552506868619" }
  - { icon: "ti-youtube", link: "https://www.youtube.com/channel/UCOGnDzu9lCxjc55izu3rCxg" }
  - { icon: "ti-wordpress", link: "https://www.tiktok.com/@chipmastervn?is_from_webapp=1&sender_device=pc" }
  - { icon: "ti-pinterest", link: "https://pin.it/7vtQl2p" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: ChipMaster Việt Nam là một chương trình đào tạo chuyên sâu nhằm trang bị cho bạn những kỹ năng và kiến thức cần thiết để thiết kế và phát triển các vi mạch điện tử phức tạp. Vi mạch là cơ sở của hầu hết các thiết bị điện tử hiện đại, từ máy tính đến điện thoại di động và hệ thống nhúng, IoT và chúng tôi sẽ giúp bạn hiểu và áp dụng các nguyên tắc thiết kế vi mạch toàn trình để tạo ra các sản phẩm đột phá.

blurb-btn-link: "/about"
blurb-btn-name: Về Chúng Tôi

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
# team:
#   - title: "Jack Schenziwe"
#     image: "assets/images/team/member-1.png"
#     designation: "Project Manager"

#   - title: "Julias Carlie"
#     image: "assets/images/team/member-2.png"
#     designation: "Web Developer"

#   - title: "John Doe"
#     image: "assets/images/team/member-3.png"
#     designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Quan tâm tới
skills:
  - { name: Công nghệ phần mềm ô tô - xe điện, color: "#fdb157", value: "90%" }
  - { name: Công nghệ Vi Mạch, color: "#9473e6", value: "80%" }
  - { name: Công nghệ Robot, color: "#bdecf6", value: "60%" }
  - { name: Công nghệ IoT & AI, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Đào tạo
experience:
  - {
      name: Thiết kế và phân tích hệ thống Nhúng,
      icon: "icon-1.png",
      # date: "Jan 2007 - Feb 2009",
      # organization: "WEBEX",
    }
  - {
      name: Thiết kế vi mạch,
      icon: "icon-2.png",
      # date: "Mar 2009 - Aug 2014",
      # organization: "AUGMEDIX",
    }
  - {
      name: Thiết kế hệ thống IoT & AI,
      icon: "icon-3.png",
      # date: "Sep 2014 - Present",
      # organization: "THEMEFISHER",
    }
  - {
      name: Lập trình FPGA,
      icon: "icon-1.png",
      # date: "Sep 2014 - Present",
      # organization: "THEMEFISHER",
    }

#-------------------------------
# Education Section

education-title: Vì sao nên chọn chúng tôi
education:
  - {
      name: Hình thức học tập linh hoạt - tiết kiệm chi phí,
      # date: "2006",
      # organization: "Masassusets Institute of Technology",
    }
  - {
      name: Hệ thống giáo trình chuẩn quốc tế - tài liệu trực tuyến - mã nguồn phong phú cập nhật mới nhất,
      # date: "2004",
      # organization: "Harvard University",
    }
  - {
      name: Đội ngũ giảng viên giỏi - giàu kinh nghiệm,
      # date: "2000",
      # organization: "Cardiff School",
    }
  - {
      name: Cung cấp giải pháp nhanh - hiệu quả - chi phí hợp lý,
      # date: "1998",
      # organization: "Cardiff School",
    }

#-------------------------------
# Services Section

services-title: Dịch vụ
services:
  - {
      name: Cung cấp giải pháp phần mềm,
      icon: ti-palette,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: ,# Add true to select section
    }
  - {
      name: Đào tạo nhân lực,
      icon: ti-vector,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: true, # Add true to select section
    }
  - {
      name: Tư vấn dự án,
      icon: ti-panel,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: ,# Add true to select section
    }

#-------------------------------
# Documents (Section and Page)

# Documents Home Section
documents-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Documents Page
documents-label:
  - { title: "Tài liệu miễn phí", type: "design" }
  - { title: "Review Sách", type: "branding" }
  - { title: "Các Công Cụ Hay Dùng", type: "illustration" }

documents-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    documents-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    documents-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    documents-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    documents-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    documents-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    documents-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    documents-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    documents-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    documents-type:
      - type: "illustration"

# Services Page
services-label:
  - { title: "Đào Tạo", type: "design" }
  - { title: "Cung Cấp Giải Pháp", type: "branding" }
  - { title: "Tư Vấn Dự Án", type: "illustration" }

services-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    services-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    services-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    services-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    services-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    services-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    services-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    services-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    services-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    services-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Nguyễn Hoàng Dương"
    image: "assets/images/testimonial/client-1.png"
    designation: "Sinh viên"
    content: "ChipMaster Việt Nam cung cấp một nền tảng vững chắc về lập trình nhúng. Từ các khái niệm cơ bản như vi điều khiển, cảm biến, giao tiếp và điều khiển thiết bị, cho đến các kỹ thuật nâng cao như lập trình trực tiếp trên phần cứng và quản lý tài nguyên, tôi đã có cơ hội hiểu rõ về lập trình nhúng và ứng dụng nó vào các đồ án môn học."

  - name: "Lâm Trịnh"
    image: "assets/images/testimonial/client-1.png"
    designation: "Người đi làm"
    content: "ChipMaster Việt Nam đã giới thiệu cho tôi các công cụ và phần mềm phổ biến để thiết kế, mô phỏng và kiểm thử vi mạch. Việc được thực hành và tiếp xúc với các dự án thực tế trên vi mạch đã giúp tôi áp dụng kiến thức lý thuyết vào thực tiễn và phát triển kỹ năng thiết kế cũng như kiểm thử vi mạch."

  - name: "Phan Thanh Hoàng"
    image: "assets/images/testimonial/client-1.png"
    designation: "Sinh viên năm 3"
    content: "Giảng viên và nhóm hỗ trợ của khóa học đã rất tận tâm và am hiểu về lĩnh vực này. Họ đã truyền đạt kiến thức một cách rõ ràng và tổ chức các hoạt động học tập một cách hợp lý. Tôi đã nhận được sự hỗ trợ và giúp đỡ khi gặp khó khăn trong quá trình học."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Thông tin liên lạc
contact-email: chipmastervn@gmail.com
